repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.5.0
    hooks:
    - id: trailing-whitespace
    - id: check-added-large-files
    - id: check-yaml
    - id: check-toml
    - id: check-json

  - repo: local
    hooks:
      - id: ruff-format
        name: ruff-format
        entry: ruff format --force-exclude
        language: python
        types_or: [python, pyi]
        require_serial: true

      - id: mypy
        name: mypy
        entry: mypy
        language: python
        types_or: [python, pyi]
        pass_filenames: false
        require_serial: true

      - id: ruff
        name: ruff
        entry: ruff check --force-exclude
        language: python
        types_or: [python, pyi]
        require_serial: true
